# Generated by Django 4.0.4 on 2022-06-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(max_length=50)),
                ('eventDescription', models.TextField()),
                ('eventDate', models.DateField()),
                ('eventPoster', models.ImageField(upload_to='posters/%Y/%m/%d/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventPrice', models.IntegerField(default=0)),
                ('forEvent', models.ManyToManyField(to='tickets.events')),
            ],
        ),
        migrations.CreateModel(
            name='TicketsSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holdersName', models.CharField(max_length=30)),
                ('holdersEmail', models.EmailField(max_length=254)),
                ('holdersPhoneNumber', models.IntegerField()),
                ('ticketVerificationCode', models.CharField(max_length=50)),
                ('event', models.ManyToManyField(to='tickets.events')),
                ('price', models.ManyToManyField(to='tickets.prices')),
            ],
        ),
    ]
